CREATE TABLE DAILYQUIZZES
(
    quiz_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-increment ID
    question      VARCHAR2(255) NOT NULL,                              -- Quiz question
    question_type NUMBER(1)     NOT NULL,                              -- Question type (1,2,3,4)
    option1       VARCHAR2(255),                                       -- Choice 1
    option2       VARCHAR2(255),                                       -- Choice 2
    option3       VARCHAR2(255),                                       -- Choice 3
    option4       VARCHAR2(255),                                       -- Choice 4
    answer        NUMBER(1)     NOT NULL,                              -- Correct answer (1,2,3,4)
    quiz_date     TIMESTAMP     NOT NULL,                              -- Quiz date
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,                      -- Creation timestamp
    updated_at    TIMESTAMP,                                           -- Update timestamp
    deleted_at    TIMESTAMP default NULL                               -- Deletion timestamp (nullable)
);