CREATE TABLE STOCKS (
                        ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 주식 고유 ID (자동 증가)
                        TICKER        VARCHAR2(20) NOT NULL UNIQUE,  -- 주식 티커 (유니크)
                        NAME          VARCHAR2(100) NOT NULL,       -- 주식명
                        PROBABILITY   NUMBER(3) NOT NULL CHECK (PROBABILITY BETWEEN 1 AND 100), -- 지급 확률 (정수값)
                        DETAIL        VARCHAR2(500),               -- 주식 설명
                        CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP, -- 생성일
                        UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP, -- 업데이트일
                        DELETED_AT    TIMESTAMP NULL               -- 삭제일 (NULL이면 활성 상태)
);