CREATE TABLE USERS
(
    UUID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 회원 고유번호 (기본 키)
    USERNAME   VARCHAR2(20) NOT NULL UNIQUE,                        -- 회원 ID (유니크)
    PASSWORD   VARCHAR2(64) NOT NULL,                               -- 비밀번호
    ACCOUNT_ID VARCHAR2(20) NOT NULL,                               -- 계좌번호
    POINT      NUMBER    DEFAULT 0,                                 -- 포인트 (기본값 0)
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,                      -- 생성일 (자동 설정)
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,                      -- 업데이트일 (자동 설정)
    DELETED_AT TIMESTAMP    NULL                                    -- 삭제일 (NULL 허용)
);